Feature/badge
Gankster/TestGuru pull request #17
Opened 2021-04-04 17:47 UTC by Gankster

2021-04-04 18:28 UTC, BubuntuClu requested changes

2021-04-04 18:28 UTC, BubuntuClu commented on app/controllers/badges_controller.rb
> +    @badges = current_user.badges.uniq
вчем разница между этими бейджами. есть смысл выводить все доступные бейджи и бейджи которые пользователь получил. а тут что-то странное случилось вывести

2021-04-04 18:28 UTC, BubuntuClu commented on app/controllers/passing_tests_controller.rb
> +    @received_badges = Badge.where(id: cookies[:received_badge_ids])
ты же можешь просто флэш сообщение сделать в `update` методе, тогда сессии и запросы в БД будут не нужны

2021-04-04 18:28 UTC, BubuntuClu commented on app/services/badge_check_service.rb
> +    return [] unless @passing_test.test_passed?
это стоит вынести выше, в контроллер, чтобы вообще не дергать сервис если тест не пройден. а сейчас ты дерагаешь сервис, получаешь все бейджи из БД, а потом такой, упс оно оказалось не нужно

2021-04-04 18:28 UTC, BubuntuClu commented on app/services/badge_check_service.rb
> +    passed_test_ids = passed_tests.in_category(category)
данные получай полностью через запрос к БД, а не через обработку рубями.

2021-04-04 18:28 UTC, BubuntuClu commented on app/services/badge_check_service.rb
> +    passed_test_ids = passed_tests.by_level(level)
и тут тоже через БД

2021-04-04 18:28 UTC, BubuntuClu commented on app/services/badge_check_service.rb
> +    prev_passed_tests.where(test: @passing_test.test).empty?
зачем знать как был пройден прошлый тест? тут достаточно понимать сколько раз проходился тест

2021-04-04 18:28 UTC, BubuntuClu commented on app/services/badge_check_service.rb
> +  def passed_first_try?(test_id)
а как ты сюда зашиваешь значение ID пройденного теста? ты создал бейдж и присвоил ему какой-то ID для проверки "прошел ли с первого раза". создал новый тест и его проходишь. тут получается не получить бейдж для нового теста? только для конкретного? как-то очень узко получилось. сделай так чтобы можно было для любого теста получить бейдж "пройден с первого раза"

2021-04-04 18:31 UTC, BubuntuClu requested changes

2021-04-04 18:31 UTC, BubuntuClu commented on app/controllers/passing_tests_controller.rb
> +      current_user.badges.push(received_badges)
это тоже можно занести в сервис

2021-04-04 18:31 UTC, BubuntuClu commented on app/services/badge_check_service.rb
> +    @badges = Badge.all
инстанс переменную делаешь только чтобы в нее выборку положить? это для чего? можно же просто в `call` методе сделать `Badge.all`

2021-04-04 18:31 UTC, BubuntuClu commented on app/services/badge_check_service.rb
> +    @badges.select { |badge| passed?(badge.rule) }
```
Badge.all.each do |badge|
  user.badges << badge if send("passed_#{badge_rule.kind}?", badge_rule.value)
end
```

если надо сформировать флэш сообщение тут можешь вернуть названия бейджей что пользователь получил

2021-04-08 07:50 UTC, Gankster commented on app/controllers/badges_controller.rb
> +    @badges = current_user.badges.uniq
Да, тупанул

2021-04-08 07:54 UTC, Gankster commented on app/services/badge_check_service.rb
> +  def passed_first_try?(test_id)
Неправильно понял задание. Сначала подумал что нужно для конкретного теста проверять "прохождение с первого раза", а так как рулы объявленные заранее, от я и создал несколько для проверки некоторых тестов

2021-04-08 19:38 UTC, BubuntuClu commented on app/services/badge_check_service.rb
> +    user.passing_tests.where(test: passing_test.test).where.not(id: passing_test.id).count.zero?
`user. passing_tests.where(test: passing_test.test).count == 1`

2021-04-08 19:38 UTC, BubuntuClu commented on app/services/badge_check_service.rb
> +    return false unless category.id == passing_test.test.category_id
unless лучше стараться избегать, так как его сложнее воспринимать - `if !=`

2021-04-09 16:09 UTC, merged